'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmployeeDetail
    Public Property EmpId As Integer
    Public Property EmpName As String
    Public Property DateOfBirth As Nullable(Of Date)
    Public Property Emailid As String
    Public Property Gender As String
    Public Property Address As String
    Public Property pinCode As String

End Class
